import pandas as pd

In [1]:
import requests
url = "https://api.openweathermap.org/data/2.5/weather"

list_cities = []
cities = [
    "Cairo",
    "Giza",
    "Alexandria",
    "Port Said",
    "Suez",
    "Ismailia",
    "Mansoura",
    "Tanta",
    "Luxor",
    "Aswan"
]
for city in cities:
    
    print(city)

    params = {
    "appid": "6a13e61e853763292101962a026aa3e8",
    "q": city
    }
    response = requests.get(url, params=params)
    data = response.json()
    city = city
    country = 'Egypt'
    lat = data['coord']['lat']
    lon = data['coord']['lon']
    temp = data['main']['temp']
    pressure = data['main']['pressure']
    Humidity = data['main']['humidity']
    wind_speed = data['wind']['speed']
    list_cities.append([city, country, lat, lon, temp, pressure, Humidity, wind_speed])



print(list_cities)

Cairo
Giza
Alexandria
Port Said
Suez
Ismailia
Mansoura
Tanta
Luxor
Aswan
[['Cairo', 'Egypt', 30.0626, 31.2497, 299.57, 1016, 61, 8.23], ['Giza', 'Egypt', 30.0081, 31.2109, 299.56, 1016, 58, 3.33], ['Alexandria', 'Egypt', 31.2156, 29.9553, 298.96, 1018, 63, 5.59], ['Port Said', 'Egypt', 31.2565, 32.2841, 299.52, 1016, 71, 5.68], ['Suez', 'Egypt', 29.9737, 32.5263, 299.22, 1016, 66, 3.24], ['Ismailia', 'Egypt', 30.6043, 32.2723, 299.49, 1016, 68, 3.56], ['Mansoura', 'Egypt', 34.8616, -1.3394, 291.94, 1021, 68, 2.06], ['Tanta', 'Egypt', 30.7885, 31.0019, 299.07, 1017, 67, 3.13], ['Luxor', 'Egypt', 25.6989, 32.6421, 306.18, 1013, 25, 2.06], ['Aswan', 'Egypt', 24.0934, 32.907, 306.76, 1012, 21, 2.57]]

In [2]:
import pandas as pd
df = pd.DataFrame(list_cities, columns=['City', 'Country', 'Latitude', 'Longitude', 'Temperature', 'Pressure', 'Humidity', 'Wind Speed'])
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed
0,Cairo,Egypt,30.0626,31.2497,299.57,1016,61,8.23
1,Giza,Egypt,30.0081,31.2109,299.56,1016,58,3.33
2,Alexandria,Egypt,31.2156,29.9553,298.96,1018,63,5.59
3,Port Said,Egypt,31.2565,32.2841,299.52,1016,71,5.68
4,Suez,Egypt,29.9737,32.5263,299.22,1016,66,3.24
5,Ismailia,Egypt,30.6043,32.2723,299.49,1016,68,3.56
6,Mansoura,Egypt,34.8616,-1.3394,291.94,1021,68,2.06
7,Tanta,Egypt,30.7885,31.0019,299.07,1017,67,3.13
8,Luxor,Egypt,25.6989,32.6421,306.18,1013,25,2.06
9,Aswan,Egypt,24.0934,32.9070,306.76,1012,21,2.57

In [3]:
def fun1(city):
  if city in ["Luxor", "Aswan"]:
    return 'Upper'
  else:
    return 'Lower'
df['Region'] = df['City'].apply(fun1)
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region
0,Cairo,Egypt,30.0626,31.2497,299.57,1016,61,8.23,Lower
1,Giza,Egypt,30.0081,31.2109,299.56,1016,58,3.33,Lower
2,Alexandria,Egypt,31.2156,29.9553,298.96,1018,63,5.59,Lower
3,Port Said,Egypt,31.2565,32.2841,299.52,1016,71,5.68,Lower
4,Suez,Egypt,29.9737,32.5263,299.22,1016,66,3.24,Lower
5,Ismailia,Egypt,30.6043,32.2723,299.49,1016,68,3.56,Lower
6,Mansoura,Egypt,34.8616,-1.3394,291.94,1021,68,2.06,Lower
7,Tanta,Egypt,30.7885,31.0019,299.07,1017,67,3.13,Lower
8,Luxor,Egypt,25.6989,32.6421,306.18,1013,25,2.06,Upper
9,Aswan,Egypt,24.0934,32.9070,306.76,1012,21,2.57,Upper

In [4]:
df['Temperature'] = df['Temperature'] - 270
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region
0,Cairo,Egypt,30.0626,31.2497,29.57,1016,61,8.23,Lower
1,Giza,Egypt,30.0081,31.2109,29.56,1016,58,3.33,Lower
2,Alexandria,Egypt,31.2156,29.9553,28.96,1018,63,5.59,Lower
3,Port Said,Egypt,31.2565,32.2841,29.52,1016,71,5.68,Lower
4,Suez,Egypt,29.9737,32.5263,29.22,1016,66,3.24,Lower
5,Ismailia,Egypt,30.6043,32.2723,29.49,1016,68,3.56,Lower
6,Mansoura,Egypt,34.8616,-1.3394,21.94,1021,68,2.06,Lower
7,Tanta,Egypt,30.7885,31.0019,29.07,1017,67,3.13,Lower
8,Luxor,Egypt,25.6989,32.6421,36.18,1013,25,2.06,Upper
9,Aswan,Egypt,24.0934,32.9070,36.76,1012,21,2.57,Upper

In [5]:
def categ(city):
    for city in df['City']:
        return 'Hot'
df['Temperature Category'] = df['City'].apply(categ)
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region,Temperature Category
0,Cairo,Egypt,30.0626,31.2497,29.57,1016,61,8.23,Lower,Hot
1,Giza,Egypt,30.0081,31.2109,29.56,1016,58,3.33,Lower,Hot
2,Alexandria,Egypt,31.2156,29.9553,28.96,1018,63,5.59,Lower,Hot
3,Port Said,Egypt,31.2565,32.2841,29.52,1016,71,5.68,Lower,Hot
4,Suez,Egypt,29.9737,32.5263,29.22,1016,66,3.24,Lower,Hot
5,Ismailia,Egypt,30.6043,32.2723,29.49,1016,68,3.56,Lower,Hot
6,Mansoura,Egypt,34.8616,-1.3394,21.94,1021,68,2.06,Lower,Hot
7,Tanta,Egypt,30.7885,31.0019,29.07,1017,67,3.13,Lower,Hot
8,Luxor,Egypt,25.6989,32.6421,36.18,1013,25,2.06,Upper,Hot
9,Aswan,Egypt,24.0934,32.9070,36.76,1012,21,2.57,Upper,Hot

In [6]:
def hum(Humidity):
    if Humidity < 30:
        return 'Dry'
    elif Humidity >=30 & Humidity <=60:
        return 'Comfortable'
    else:
        return 'Humid'

df['Humidity Category'] = df['Humidity'].apply(hum)
df

,City,Country,Latitude,Longitude,Temperature,Pressure,Humidity,Wind Speed,Region,Temperature Category,Humidity Category
0,Cairo,Egypt,30.0626,31.2497,29.57,1016,61,8.23,Lower,Hot,Comfortable
1,Giza,Egypt,30.0081,31.2109,29.56,1016,58,3.33,Lower,Hot,Comfortable
2,Alexandria,Egypt,31.2156,29.9553,28.96,1018,63,5.59,Lower,Hot,Comfortable
3,Port Said,Egypt,31.2565,32.2841,29.52,1016,71,5.68,Lower,Hot,Comfortable
4,Suez,Egypt,29.9737,32.5263,29.22,1016,66,3.24,Lower,Hot,Comfortable
5,Ismailia,Egypt,30.6043,32.2723,29.49,1016,68,3.56,Lower,Hot,Comfortable
6,Mansoura,Egypt,34.8616,-1.3394,21.94,1021,68,2.06,Lower,Hot,Comfortable
7,Tanta,Egypt,30.7885,31.0019,29.07,1017,67,3.13,Lower,Hot,Comfortable
8,Luxor,Egypt,25.6989,32.6421,36.18,1013,25,2.06,Upper,Hot,Dry
9,Aswan,Egypt,24.0934,32.9070,36.76,1012,21,2.57,Upper,Hot,Dry

In [7]:
data = list(df.itertuples(index = None, name = None))

In [8]:
import pyodbc
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=depi12462.database.windows.net;"
    "database=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
)
 
cursor = conn.cursor()
cursor.execute('''Create Table Habiba2 
                (
                City varchar(50),
                Country varchar(50),
                Latitude varchar(50),
                Logitude  varchar(50),
                Temperature varchar(50),
                Pressure varchar(50),
                Humidity varchar(50),
                WindSpeed varchar(50),
                Region	varchar(50),
                TemperatureCategory varchar(50),
                HumidityCategory varchar(50)
                )
                                        ''')

cursor.close()

conn.commit()
conn.close()

In [9]:
cursor = conn.cursor()

ProgrammingError: Attempt to use a closed connection.

In [10]:
import pyodbc
conn = pyodbc.connect(                    
    "driver={ODBC Driver 17 for SQL Server};"
    "server=depi12462.database.windows.net;"
    "database=Depi;"
    "UID=sqladmin;"
    "PWD=Depi123#;"
)
 
cursor = conn.cursor()
cursor.executemany('Insert Into Habiba2 Values(?,?,?,?,?,?,?,?,?,?,? )', data)

cursor.close()

conn.commit()
conn.close()